[package]
name = "porter-process"
version.workspace = true
edition.workspace = true

[[bin]]
name = "process"
path = "src/main.rs"

[dependencies]
ktls = { version = "6.0.2", default-features = false, features = ["ring", "tls12"] }
libc = "0.2.189"
sendfd = { version = "0.4.4", features = ["tokio"] }
tokio.workspace = true
rustls = { version = "0.23.45", default-features = false, features = ["ring", "tls12"] }
tokio-rustls = { version = "0.26.5", default-features = false, features = ["ring", "tls12"] }
